### ISSUE TITLE
How does the line numbering work?

### ISSUE THREAD

**Issue by kajdreef** [spideruci/blinky#2]
I'm currently analyzing a simple java program that recursively calls a function 4 times.
After the 4th time the function exists.

```
class Main{
  public static void main(String[] arg){
    RandomClass rc = new RandomClass(3);
    rc.run();
  }
}
```
```
class RandomClass{
  int value;
  public RandomClass(int number){
    this.value = number;
  }

  public void run(){
    if(this.value > 0){
      this.value--;
      this.run();
    }
  }
}
```
[Original output](https://github.com/spideruci/blinky/files/205559/trace_input.txt)
[After running the postprocessing on it](https://github.com/spideruci/blinky/files/205560/output.txt)

If I compare the last two times we entered *run()* the line number is different (7 or 8). Is this because it enters and directly ends and because of that it is 8?

```
$[a-z]+$, ClassName, MethodName, ThreadID, LineNumber, StackDepth
$enter$, RandomClass, run()V, 1, 7, 5
$enter$, RandomClass, run()V, 1, 8, 6
```

**Comment by VijayKrishna** [comment]
Short answer: Instruction-Execution-Events do not report the source line number of the Instruction (byte code or source code) that got executed. So in fact, the `7` and `8` here refer to the time-stamps of the Instruction-Execution-Events (time elapsed in milliseconds since the program-under-analysis started execution), not line numbers of the executed Instruction.

Long Answer:
> If I compare the last two times we entered run() the line number is different (7 or 8). Is this because it enters and directly ends and because of that it is 8?

So, i imagine that you are looking at the logs for Instruction-Execution-Events in the trace file when you ask this question. Specifically, i imagine that you are referring to these logs in the trace file that you supplied:

```
$$$,8,1,7,118352462,13,$enter$,NA
$$$,10,1,7,118352462,13,$enter$,NA
$$$,12,1,7,118352462,13,$enter$,NA
$$$,14,1,8,118352462,13,$enter$,NA
```

Here the `7` and `8` refer to the number of milliseconds that have passed since the program started to execute.. specifically the time elapsed since the `public static void main(String[] args)` method started execution.
